// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-orders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function normalize(v) {
  return String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
}
function matches(field, search) {
  if (!search) return true;
  const h = normalize(field);
  return normalize(search).split(/\s+/).filter(Boolean).every((t) => h.includes(t));
}
var search_orders_default = defineTool({
  name: "search_orders",
  title: "Buscar pedidos",
  description: "Busca pedidos de Bionovations por cliente, producto, estado de producci\xF3n, marca o asesor. Devuelve datos filtrados por los permisos (RLS) del usuario.",
  inputSchema: {
    client: z.string().optional().describe("Nombre del cliente (b\xFAsqueda parcial, sin tildes)"),
    product: z.string().optional().describe("Nombre del producto (b\xFAsqueda parcial)"),
    production_status: z.enum([
      "pendiente",
      "diseno",
      "produccion_cuerpos",
      "estampacion",
      "dosificacion",
      "sellado",
      "recorte",
      "empaque",
      "listo",
      "despachado",
      "entregado"
    ]).optional(),
    brand: z.enum(["magical_warmers", "sweatspot"]).optional(),
    advisor: z.string().optional().describe("Nombre del asesor"),
    limit: z.number().int().min(1).max(30).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const hasText = Boolean(args.client || args.product || args.advisor);
    let q = sb(ctx).from("orders").select(
      "id, brand, client_name, product, quantity, total_amount, abono, payment_complete, production_status, advisor_name, created_at, delivery_date, dispatched_at, transportadora, numero_guia, invoice_number, invoice_status, sale_type"
    ).order("created_at", { ascending: false }).limit(hasText ? 500 : args.limit);
    if (args.production_status) q = q.eq("production_status", args.production_status);
    if (args.brand) q = q.eq("brand", args.brand);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).filter((o) => matches(o.client_name, args.client)).filter((o) => matches(o.product, args.product)).filter((o) => matches(o.advisor_name, args.advisor)).slice(0, args.limit);
    return {
      content: [{ type: "text", text: `Se encontraron ${orders.length} pedidos.` }],
      structuredContent: { count: orders.length, orders }
    };
  }
});

// src/lib/mcp/tools/get-inventory.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.1";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function normalize2(v) {
  return String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
}
var get_inventory_default = defineTool2({
  name: "get_inventory",
  title: "Consultar inventario",
  description: "Consulta existencias en stock_items por nombre, marca o categor\xEDa. Marca opcional bajo m\xEDnimo.",
  inputSchema: {
    query: z2.string().optional().describe("Buscar por nombre (parcial)"),
    brand: z2.enum(["magical_warmers", "sweatspot"]).optional(),
    category: z2.string().optional().describe("p.ej. cuerpos_referencias, producto_terminado, materia_prima"),
    low_stock_only: z2.boolean().default(false),
    limit: z2.number().int().min(1).max(80).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sb2(ctx).from("stock_items").select("name, brand, category, color, product_type, available, in_process, min_stock, unit").order("name").limit(args.query ? 500 : args.limit);
    if (args.brand) q = q.eq("brand", args.brand);
    if (args.category) q = q.eq("category", args.category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let items = (data ?? []).filter((i) => {
      if (!args.query) return true;
      return normalize2(i.name).includes(normalize2(args.query));
    });
    if (args.low_stock_only) {
      items = items.filter((i) => Number(i.available) <= Number(i.min_stock));
    }
    items = items.slice(0, args.limit);
    return {
      content: [{ type: "text", text: `Se encontraron ${items.length} items.` }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-production-tasks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.1";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function normalize3(v) {
  return String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
}
var get_production_tasks_default = defineTool3({
  name: "get_production_tasks",
  title: "Tareas de producci\xF3n",
  description: "Consulta tareas de producci\xF3n activas (production_orders).",
  inputSchema: {
    brand: z3.enum(["magical_warmers", "sweatspot"]).optional(),
    current_stage: z3.string().optional().describe("estampacion, dosificacion, sellado, recorte, empaque, listo, etc."),
    stage_status: z3.enum(["pendiente", "en_proceso", "completado"]).optional(),
    molde: z3.string().optional().describe("Filtro por molde/referencia (parcial)"),
    limit: z3.number().int().min(1).max(40).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sb3(ctx).from("production_orders").select(
      "id, brand, client_name, quantity, current_stage, stage_status, workflow_type, molde, gel_color, ink_color, thermo_size, created_at, completed_at"
    ).order("created_at", { ascending: false }).limit(args.molde ? 500 : args.limit);
    if (args.brand) q = q.eq("brand", args.brand);
    if (args.current_stage) q = q.eq("current_stage", args.current_stage);
    if (args.stage_status) q = q.eq("stage_status", args.stage_status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const tasks = (data ?? []).filter((t) => args.molde ? normalize3(t.molde).includes(normalize3(args.molde)) : true).slice(0, args.limit);
    return {
      content: [{ type: "text", text: `Se encontraron ${tasks.length} tareas.` }],
      structuredContent: { count: tasks.length, tasks }
    };
  }
});

// src/lib/mcp/tools/get-advisor-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.102.1";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_advisor_summary_default = defineTool4({
  name: "get_advisor_summary",
  title: "Resumen por asesor",
  description: "Resumen de ventas por asesor: pedidos, total vendido, cobrado y pendiente.",
  inputSchema: {
    advisor: z4.string().optional().describe("Nombre del asesor (parcial)"),
    since: z4.string().optional().describe("Fecha inicio ISO YYYY-MM-DD"),
    until: z4.string().optional().describe("Fecha fin ISO YYYY-MM-DD")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sb4(ctx).from("orders").select(
      "advisor_name, total_amount, abono, payment_complete, payment_method, sale_type, payment_proof_url, created_at"
    );
    if (args.advisor) q = q.ilike("advisor_name", `%${args.advisor}%`);
    if (args.since) q = q.gte("created_at", args.since);
    if (args.until) q = q.lte("created_at", args.until);
    const { data, error } = await q.limit(2e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const map = /* @__PURE__ */ new Map();
    for (const o of data ?? []) {
      const k = o.advisor_name ?? "\u2014";
      const cur = map.get(k) ?? { advisor: k, orders: 0, total: 0, cobrado: 0, pendiente: 0 };
      const total = Number(o.total_amount) || 0;
      const paid = o.payment_complete || o.payment_method === "pagado" || o.payment_method === "obsequio" || o.sale_type === "menor" && o.payment_proof_url ? total : Math.min(Number(o.abono) || 0, total);
      cur.orders += 1;
      cur.total += total;
      cur.cobrado += paid;
      cur.pendiente += Math.max(total - paid, 0);
      map.set(k, cur);
    }
    const summary = Array.from(map.values()).sort((a, b) => b.total - a.total);
    return {
      content: [{ type: "text", text: `Resumen para ${summary.length} asesor(es).` }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "auncgjkpwajfbvcckuny";
var mcp_default = defineMcp({
  name: "bionovations-mcp",
  title: "Bionovations MCP",
  version: "0.1.0",
  instructions: "Herramientas internas de Bionovations SAS (Magical Warmers y Sweatspot). Consulta pedidos, inventario, tareas de producci\xF3n y res\xFAmenes por asesor. Los resultados respetan los permisos del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_orders_default, get_inventory_default, get_production_tasks_default, get_advisor_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
