ALTER TABLE public.stock_items DROP CONSTRAINT IF EXISTS stock_items_name_brand_category_type_unique;
DROP INDEX IF EXISTS public.stock_items_name_brand_category_type_unique;
DROP INDEX IF EXISTS public.stock_items_canonical_uniq;

DELETE FROM public.stock_items WHERE brand = 'sweatspot' AND category = 'producto_terminado';

INSERT INTO public.stock_items (brand, category, name, color, logo, product_type, sweatspot_category, available, min_stock, unit) VALUES
('sweatspot','producto_terminado','CANGURO BOTELLA','Negro','Sweatspot','IMPORTADO','canguros',31,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO BIB NUMBER TRAIL TALLA L','Negro','Sweatspot','IMPORTADO','canguros',1,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO BIB NUMBER TRAIL TALLA M','Negro','Sweatspot','IMPORTADO','canguros',149,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO BIB NUMBER TRAIL TALLA S','Negro','Sweatspot','IMPORTADO','canguros',139,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO BIF NUMBER TRAIL TALLA XL','Negro','Sweatspot','IMPORTADO','canguros',53,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO BIB NUMBER','Negro','Sweatspot','IMPORTADO','canguros',133,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO FREE BELT NEGRO TALLA L','Negro','Sweatspot','IMPORTADO','canguros',99,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO FREE BELT ROSADO TALLA S','Negro',NULL,'IMPORTADO','canguros',55,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO FREE BELT ROSADO TALLA M','Negro',NULL,'IMPORTADO','canguros',61,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO FREE BELT AZUL TALLA S','Negro',NULL,'IMPORTADO','canguros',8,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO IMPERMEABLE NEGRO','Negro',NULL,'IMPORTADO','canguros',143,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO IMPERMEABLE ROSADO','Negro',NULL,'IMPORTADO','canguros',3,0,'Unidades'),
('sweatspot','producto_terminado','CANGURO IMPERMEABLE AZUL','Negro',NULL,'IMPORTADO','canguros',1,0,'Unidades'),
('sweatspot','producto_terminado','CHALECOS','Negro',NULL,'CHALECOS','chalecos',6,0,'Unidades'),
('sweatspot','producto_terminado','BIB SPOT IMANES NEGROS','Negro','Sweatspot','IMPORTADO','accesorios',208,0,'Unidades'),
('sweatspot','producto_terminado','BIB SPOT IMANES BLANCOS','Blanco','Sweatspot','IMPORTADO','accesorios',69,0,'Unidades'),
('sweatspot','producto_terminado','MANGAS-Freezii','Negro','Sweatspot','IMPORTADO','accesorios',350,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 AMARILLO','AMARILLO','Sweatspot','IMPORTADO','termos_150',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AMARILLO','AMARILLO',NULL,'IMPORTADO','termos_250',0,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AMARILLO','AMARILLO','Sweatspot','IMPORTADO','termos_250',0,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AMARILLO CORREA','AMARILLO','Sweatspot','IMPORTADO','termos_250',4,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 AMARILLO','AMARILLO','Sweatspot','IMPORTADO','termos_500',0,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 AMARILLO CORREA','AMARILLO','Sweatspot','IMPORTADO','termos_500',5,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 AZUL','AZUL','Sweatspot','NACIONAL','termos_150',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 AZUL','AZUL',NULL,'NACIONAL','termos_150',0,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AZUL','AZUL','Sweatspot','NACIONAL','termos_250',147,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AZUL','AZUL',NULL,'NACIONAL','termos_250',12,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AZUL CORREA','AZUL','Sweatspot','NACIONAL','termos_250',0,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AZUL JUGUETON','AZUL','Sweatspot','NACIONAL','termos_250',9,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AZUL CLARO','AZUL CLARO','Sweatspot','IMPORTADO','termos_250',16,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 AZUL CLARO','AZUL CLARO',NULL,'IMPORTADO','termos_250',29,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 MORADO','MORADO','Sweatspot','NACIONAL','termos_150',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 MORADO','MORADO','Sweatspot','NACIONAL','termos_250',75,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 MORADO CORREA','MORADO','Sweatspot','NACIONAL','termos_250',19,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 MORADO','MORADO',NULL,'NACIONAL','termos_250',45,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 MORADO','MORADO','Sweatspot','NACIONAL','termos_500',36,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 MORADO CORREA','MORADO','Sweatspot','NACIONAL','termos_500',3,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 MORADO JUGUETON','MORADO','Sweatspot','NACIONAL','termos_250',11,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 NEGRO','NEGRO','Sweatspot','NACIONAL','termos_150',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 NEGRO','NEGRO','Sweatspot','NACIONAL','termos_250',31,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 NEGRO CORREA','NEGRO','Sweatspot','NACIONAL','termos_250',5,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 NEGRO','NEGRO',NULL,'NACIONAL','termos_250',5,0,'Unidades'),
('sweatspot','producto_terminado','TERMO NEGRO 500','NEGRO','Sweatspot','NACIONAL','termos_500',30,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROJO','ROJO','Sweatspot','IMPORTADO','termos_250',30,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROJO','ROJO',NULL,'IMPORTADO','termos_250',12,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROJO CORREA','ROJO','Sweatspot','IMPORTADO','termos_250',16,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 ROSADO','ROSADO','Sweatspot','NACIONAL','termos_150',1,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 150 ROSADO','ROSADO',NULL,'NACIONAL','termos_150',5,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROSADO','ROSADO','Sweatspot','NACIONAL','termos_250',94,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROSADO CORREA','ROSADO','Sweatspot','NACIONAL','termos_250',13,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROSADO JUGUETON','ROSADO','Sweatspot','NACIONAL','termos_250',26,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 ROSADO JUGUETON','ROSADO',NULL,'NACIONAL','termos_250',149,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 ROSADO','ROSADO','Sweatspot','NACIONAL','termos_500',27,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 ROSADO CORREA','ROSADO','Sweatspot','NACIONAL','termos_500',13,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 SALMON','SALMON','Sweatspot','IMPORTADO','termos_250',30,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 SALMON','SALMON',NULL,'IMPORTADO','termos_250',159,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 SALMON CORREA','SALMON','Sweatspot','IMPORTADO','termos_250',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 SALMON JUGUETON','SALMON','Sweatspot','IMPORTADO','termos_250',3,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 SALMON JUGUETON','SALMON',NULL,'IMPORTADO','termos_250',53,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE CLARO','VERDE CLARO',NULL,'IMPORTADO','termos_250',60,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE CLARO CORREA','VERDE CLARO','Sweatspot','IMPORTADO','termos_250',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 TRANSPARENTE','TRANSPARENTE','Sweatspot','IMPORTADO','termos_250',27,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 TRANSPARENTE','TRANSPARENTE',NULL,'IMPORTADO','termos_250',263,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 500 TRANSPARENTE','TRANSPARENTE','Sweatspot','IMPORTADO','termos_500',2,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE MILITAR','VERDE MILITAR','Sweatspot','IMPORTADO','termos_250',27,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE MILITAR','VERDE MILITAR',NULL,'IMPORTADO','termos_250',129,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE MILITAR CORREA','VERDE MILITAR','Sweatspot','IMPORTADO','termos_250',5,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE MILITAR JUGUETON','VERDE MILITAR',NULL,'IMPORTADO','termos_250',24,0,'Unidades'),
('sweatspot','producto_terminado','TERMO 250 VERDE MILITAR JUGUETON','VERDE MILITAR','Sweatspot','IMPORTADO','termos_250',25,0,'Unidades');

CREATE UNIQUE INDEX stock_items_canonical_uniq
  ON public.stock_items (
    brand, category, lower(name),
    coalesce(product_type, ''),
    coalesce(logo, ''),
    coalesce(color, '')
  );